on:
  issue_comment:
    types: [created]

jobs:
  close:
    if: contains(github.event.comment.html_url, '/issues/') && startsWith(github.event.comment.body, '/close_mlst')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const milestones = await github.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            
            // release以外のマイルストーンがある可能性を考慮（いる？）
            releaseMilestons = milestones.data.filter((mlst)=>{return mlst.title.endsWith("_release")});
            
            // 現在日時の時刻が00:00:00のDateを用意し、これより古いマイルストーンはcloseする
            now = new Date();
            today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
            closeMilestoneNumbers = [];
            
            for(mlst of releaseMilestons){
              title = mlst.title;
              
              // [0-9]{4}_[0-9]{2}_[0-9]{2}みたいな正規表現マッチでもっと簡単にできそう
              dateValues = title.split("_");
              if(dateValues.length < 4){continue;}
              yyyy = dateValues[0];
              mm = dateValues[1];
              dd = dateValues[2];
              mlstDate = new Date(yyyy + "-" + mm + "-" + dd);
              if(mlstDate.getTime() < today.getTime()){
                closeMilestoneNumbers.push(mlst.number);
              }
            }
            console.log(closeMilestoneNumbers);
            
            // close処理は次のstepに分けてもいいかも. 
            for(mlstNumber of closeMilestoneNumbers){
              github.issues.updateMilestone({
                owner: context.repo.owner,
                repo: context.repo.repo,
                milestone_number: mlstNumber,
                state: "closed"
              });
            }
            
