on:
  issue_comment:
    types: [created]

jobs:
  create:
    if: contains(github.event.comment.html_url, '/issues/') && startsWith(github.event.comment.body, '/create_mlst')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            d = new Date();
            offsetDate = 3;
            d.setDate(d.getDate()+offsetDate);
            yyyy = d.getFullYear().toString();
            mm = ("0" + d.getMonth()+1).slice(-2);
            dd = ("0" + d.getDate()).slice(-2);
            hhs = ["", "_11", "_15", "_17"];
            base = yyyy + "_" + mm + "_" + dd;
            titles = hhs.map((hh)=>{ return base + hh + "_release" });
            
            for(title of titles){
              github.issues.createMilestone({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title
              })
            }
